"""iban table

Revision ID: bfc2424089e2
Revises: f90df2d07016
Create Date: 2022-10-18 18:45:03.821405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc2424089e2'
down_revision = 'f90df2d07016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iban', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iban_iban'), 'iban', ['iban'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iban_iban'), table_name='iban')
    op.drop_table('iban')
    # ### end Alembic commands ###
